### ISSUE TITLE
Broken - app.jsx config to load map directly

### ISSUE THREAD

**Issue by Gaetanbrl** [geosolutions-it/MapStoreExtension#20]
Hi,

Today i'd just tested the master branche.

This works fine if i just open localhost:8081 and click on a map.

But, i want to get the root config.json file when i open `localhost:8081`.

In the past, we just change : 

`const appConfig = require('@mapstore/product/appConfig').default;`

by ...

```
ConfigUtils.setConfigProp("configurationFolder", "");
const appConfig = {
    ...require('@mapstore/product/appConfig').default,
    pages: [{
        name: "mapviewer",
        path: "/",
        component: require('@mapstore/product/pages/MapViewer').default
    }]
};
```
See this example : https://github.com/sigrennesmetropole/geor_tabou2_front/blob/develop/js/app.jsx

But now,` configurationFolder` is missing and this single page config don't work.

So, what is the new config to use `config.json` from MapStoreExtension root file now please ?

Thanks.

**Comment by Gaetanbrl** [comment]
This line is missing : 

ConfigUtils.setConfigProp("configurationFolder", "");

So, call localhost:8081/#/ open config.json directly with this config : 

1. add this line on top

`ConfigUtils.setConfigProp("configurationFolder", "");`

2. use single page

```
const appConfig = {
    ...require('@mapstore/product/appConfig').default,
    pages: [{
        name: "mapviewer",
        path: "/",
        component: require('@mapstore/product/pages/MapViewer').default
    }]
};
```

**Comment by offtherailz** [comment]
Yes.
I think this is a bug due to the update of `MapStoreExtension` project that not correctly followed the migration guidelines [here](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20210104-to-20210200)
I think that, in order to be in line with the current mapstore, we may need to move all configurations in `configs/` folder (so `new.json`, `config.json`, `localConfig.json` and so on...). and avoid to use `ConfigUtils.setConfigProp("configurationFolder", "");`

Also `extensions.json` should be reachable on `extensions` folder, accordingly to the new specification, anyway this may required a particlular attention because it is emulated by the back-end in this particluar project (See: https://github.com/search?q=org%3Ageosolutions-it+extensions%5C.json&type=code ) so the migration guidelines can not  be applied blindly, but need to refactor a little that part on this project.

**Comment by tdipisa** [comment]
@dsuren1 let's try to schedule a fix shortly for this.
